version: "3.8"
services:
  dynamodb-local:
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    # image: "amazon/dynamodb-local:latest"
    # container_name: dynamodb-local
    # ports:
    #   - "8000:8000"
    # volumes:
    #   - dynamodb-data:/home/dynamodblocal/data
    image: amazon/dynamodb-local
    restart: unless-stopped
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /opt/dynamodblocal
    volumes:
      - dynamodb_data:/opt/dynamodblocal
    ports:
      - "8000:8000"
    user: root
  admin:
    env_file: .env.local
    build:
      context: .
      dockerfile: ddbadmin.Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
  app:
    env_file: .env.local
    build: .
    volumes:
      - "./app:/code"
    ports:
      - "5050:5050"
    depends_on:
      - dynamodb-local
volumes:
  dynamodb_data:
    external: true
