#!/usr/bin/env python
"""
Test script to check if WeasyPrint is working properly.
This script will attempt to create a simple PDF from HTML using WeasyPrint.
"""

import sys
from io import BytesIO

try:
    from weasyprint import HTML

    print("WeasyPrint imported successfully!")
except ImportError as e:
    print(f"Failed to import WeasyPrint: {e}")
    print("Make sure WeasyPrint and its dependencies are installed correctly.")
    sys.exit(1)


def test_weasyprint():
    """Test WeasyPrint by generating a simple PDF from HTML"""
    try:
        html_content = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>WeasyPrint Test</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 2cm; }
                h1 { color: #4a4a4a; text-align: center; }
                p { line-height: 1.5; }
                .footer { text-align: center; font-size: 0.8em; margin-top: 2cm; }
            </style>
        </head>
        <body>
            <h1>WeasyPrint Test</h1>
            <p>This is a test document to verify that WeasyPrint is working correctly.</p>
            <p>If you can see this PDF, WeasyPrint is properly installed with all its dependencies!</p>
            <div class="footer">Generated by WeasyPrint Test Script</div>
        </body>
        </html>
        """

        # Generate PDF
        pdf_buffer = BytesIO()
        HTML(string=html_content).write_pdf(pdf_buffer)
        pdf_buffer.seek(0)

        # Save the PDF to a file
        with open("weasyprint_test.pdf", "wb") as f:
            f.write(pdf_buffer.read())

        print("Successfully created PDF! Check 'weasyprint_test.pdf'")
        return True

    except Exception as e:
        print(f"Error generating PDF: {e}")
        print("\nError Details:")
        import traceback

        traceback.print_exc()
        return False


if __name__ == "__main__":
    print("Testing WeasyPrint...")
    success = test_weasyprint()

    if success:
        print("\n✅ WeasyPrint is working correctly!")
        sys.exit(0)
    else:
        print("\n❌ WeasyPrint test failed. Check the error messages above.")
        sys.exit(1)
