AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.9
      BuildArchitecture: x86_64
