AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Reporting Engine - Staging - FastAPI on Lambda

Parameters:
  DynamodbUrl:
    Type: String
    Description: Url of Dynamodb instance
  DynamodbRegion:
    Type: String
    Description: Region of Dynamodb instance
  DynamodbAccessKey:
    Type: String
    Description: Access key credentials of Dynamodb instance
  DynamodbSecretKey:
    Type: String
    Description: Secret key credentials of Dynamodb instance
  FirestoreCredentials:
    Type: String
    Description: Credentials of Firestore
  MongoAuthCredentials:
    Type: String
    Description: Credentials of Mongo DB
  BqCredentialsSecretName:
    Type: String
    Description: Name of the Secrets Manager secret containing BigQuery credentials
  WeasyPrintLayerArn:
    Type: String
    Description: ARN of the WeasyPrint Lambda Layer

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "ReportingStaging"
      CodeUri: ../app
      Handler: main.handler
      Runtime: python3.13
      Timeout: 120
      MemorySize: 1536
      Environment:
        Variables:
          DYNAMODB_URL: !Ref DynamodbUrl
          DYNAMODB_REGION: !Ref DynamodbRegion
          DYNAMODB_ACCESS_KEY: !Ref DynamodbAccessKey
          DYNAMODB_SECRET_KEY: !Ref DynamodbSecretKey
          MONGO_AUTH_CREDENTIALS: !Ref MongoAuthCredentials
          FIRESTORE_CREDENTIALS: !Ref FirestoreCredentials
          BQ_CREDENTIALS_SECRET_NAME: !Ref BqCredentialsSecretName
          # WeasyPrint environment variables
          LD_LIBRARY_PATH: "/opt/lib"
          FONTCONFIG_PATH: "/opt/fonts"
          GDK_PIXBUF_MODULE_FILE: "/opt/lib/loaders.cache"
          XDG_DATA_DIRS: "/opt/lib"
          PYTHONPATH: "/var/runtime:/var/task:/opt/python/lib/python3.13/site-packages"
      Layers:
        - !Ref WeasyPrintLayerArn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BqCredentialsSecretName}*"
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
