AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Reporting Engine - Staging - FastAPI on Lambda

Parameters:
  DynamodbUrl:
    Type: String
    Description: Url of Dynamodb instance
  DynamodbRegion:
    Type: String
    Description: Region of Dynamodb instance
  DynamodbAccessKey:
    Type: String
    Description: Access key credentials of Dynamodb instance
  DynamodbSecretKey:
    Type: String
    Description: Secret key credentials of Dynamodb instance
  FirestoreCredentials:
    Type: String
    Description: Credentials of Firestore
  MongoAuthCredentials:
    Type: String
    Description: Credentials of Mongo DB
  BqCredentialsSecretName:
    Type: String
    Description: Name of the Secrets Manager secret containing BigQuery credentials
  HtmlToPdfUrl:
    Type: String
    Description: URL of the HTML to PDF conversion service

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "ReportingStaging"
      CodeUri: ../app
      Handler: main.handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          DYNAMODB_URL: !Ref DynamodbUrl
          DYNAMODB_REGION: !Ref DynamodbRegion
          DYNAMODB_ACCESS_KEY: !Ref DynamodbAccessKey
          DYNAMODB_SECRET_KEY: !Ref DynamodbSecretKey
          MONGO_AUTH_CREDENTIALS: !Ref MongoAuthCredentials
          FIRESTORE_CREDENTIALS: !Ref FirestoreCredentials
          BQ_CREDENTIALS_SECRET_NAME: !Ref BqCredentialsSecretName
          HTML_TO_PDF_SERVER_URL: !Ref HtmlToPdfUrl
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BqCredentialsSecretName}*"
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
    Metadata:
      BuildMethod: python3.9
      BuildArchitecture: x86_64

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
